### ISSUE TITLE
File Structuring [suggestion]

### ISSUE THREAD

**Issue by timsainb** [theilmbh/glab_oe_rig_tools#3]
Currently the file structure for OE rig is:

- `20190122-nyoni/B1071/blocks/201901222310-B1071-block-8-AP-2500-ML-750-Z-3150/2019-01-22_23-10-14/experiment1.kwd`
- or `date-rig/bird/blocks/date-bird-block#-location/datetime/experimen_tfiles'

Previous file structure on Barung was

- `/B1044/data/Pen06_Lft_AP200_ML1500/Site02_Z2430/Epc02_2018-06-20+19-42-08_NO_B`
- or  `bird/data/penetration#-x_y_loc/site#-x_loc/Epoch#-datetime-block_info`

The previous file structure makes more sense to me than the current one because:
- The Experiments highest level of organization is typically the bird, not the date - if we are running experiments across multiple days and need to close the rig app the highest folder changes 
- Organizing into Penetrations (X,Y) with sites (Z) as a sub-structure is how we organize the experiments
- why change what's not broken?

Opinions? @theilmbh @Darilbii @fasciae @sasen @tqgentner @MarvinT

**Comment by Darilbii** [comment]
Maintaining the previous file structure seems like the best route. Work has already been done to build pipelines for the old file structure and there appears to be no advantage for this new file structure.

Best,
D.B.

Daril E. Brown II
University of California, San Diego
Electrical Engineering, Ph.D. Candidate
debrown@eng.ucsd.edu
"Life is not a spectator sport. If you're going to spend your whole life in the grandstand just watching what goes on, in my opinion you're wasting your life." 
-Jackie Robinson, Innovator, Civil Rights Leader, Philanthropist

**Comment by MarvinT** [comment]
I'm pretty sure I commented on this when Brad was first setting up the file structure but here are my comments:
- There are definitely a lot of the features of the old format that I appreciated
- Unless the format is exactly replicated from the old structure, you're going to have to write a new parser anyways.
- The old format had a strange mix of capitals, lower case, dashes, underscores and double underscores
- Is there a reason to have a new folder for nyoni-raw instead of putting all the raw data under the raw folder like /RawData/Barung  /RawData/Bodegh /RawData/Ibon /RawData/Magpi /RawData/Manu /RawData/Vogel and /RawData/Zog?

**Comment by MarvinT** [comment]
Also, this repo should probably be migrated over to the gentnerlab account... This is definitely code that other gentner lab people will be using

**Comment by theilmbh** [comment]
I'm not going to do this, because:
- The folders for the data on the rig itself should be as close to what actually happened as possible. The reason is, looking through the experiments we've done already, there are plenty of examples where someone mistypes the bird number or leaves it at 'B999', or mistypes other information.  If we made the bird folder the highest level, we end up having folders like B999 full of recordings from many different days, at best, and overwriting the data, at worst.  What if you type in the number for someone else's bird? We are all guaranteed to continue making these mistakes. 
**It is trivial to merge bird folders from different days after the recording is done, if that's what you want to do.** Am I paranoid? Sure.  But paranoia trumps convenience when it comes to your raw data. 

- We already have more subdivisions than needed.  All of the x, y, z information is contained in the folder name, and likewise, **it is trivial to parse this information and reorganize the folders, if you must.** But, flatter is better. 

That being said, I can remove some of the extra folders.  We don't really need a "blocks" folder under the bird, and we also don't need the redundant datetime folder under the block.  This redundant datetime folder is put there by openephys, and I thought I set it not to do so, but I'll take another look. 

The reason for the nyoni-raw folder is that the gentnerlab user doesn't have permissions to write to the RawData folder on cube.  Yes, there are better ways to do this, but I just copy things to nyoni-raw and then to RawData.

**Comment by Darilbii** [comment]
Wait!

The Date time folders organization is very important for the chronic experiments. Please let me know what files you will be removing ahead of time as I intended to use parts of the code that has been written for the chronic rig. If you remove vital files for pipeline codes that already exist then you will be forcing me and potentially other labmates to recreate code that already exist simply because you thought it would be trivial to do without verifying if your assumption is correct.

**Comment by timsainb** [comment]
> The folders for the data on the rig itself should be as close to what actually happened as possible. The reason is, looking through the experiments we've done already, there are plenty of examples where someone mistypes the bird number or leaves it at 'B999', or mistypes other information. If we made the bird folder the highest level, we end up having folders like B999 full of recordings from many different days, at best, and overwriting the data, at worst. What if you type in the number for someone else's bird? We are all guaranteed to continue making these mistakes. It is trivial to merge bird folders from different days after the recording is done, if that's what you want to do. Am I paranoid? Sure. But paranoia trumps convenience when it comes to your raw data.

As long has we have some sub-structure with datetime, overwriting data is not a concern.

**Lets reopen this issue at least until we talk about it tomorrow at lab meeting. As per @MarvinT 's concern, since this is not on the GentnerLab github page only Brad has control over that, which is an issue.**

**Comment by Darilbii** [comment]
We do not have lab meeting tomorrow due to Psych’s recruitment.

But I support Tim’s point of both migrating the package to GentnerLab and re-opening the issue.
